### ISSUE TITLE
Date Range and Parameters Don't Work in IB_ScheduleRule

### ISSUE THREAD

**Issue by GudaoStudio** [MingboPeng/Ironbug#90] opened 2023-06-02 11:16 UTC
During my testing, I compared two different cases of Date Range and Parameters (Schedule Weekly) in the IB_ScheduleRule, and I found that no matter how these two values were changed, the calculation results were consistent. Fortunately, the 'values' input in IB_ScheduleRule can be used normally, but it can't finely control the air conditioning system anymore. I think this is a major issue.

I used a Zone HVAC Baseboard Convective Electric as a demonstration, which supports using Availability Schedule to control the use of Zone Equipment. The information in the picture shows that both Date Range and Parameters (Schedule Weekly) are not set as expected.

![image](https://github.com/MingboPeng/Ironbug/assets/51848364/d58d41ea-2f19-4c5d-a6e1-c056504a1f7a)

I hope this test can be helpful to you.

best.
Zhengrong

**Comment by MingboPeng** [comment] 2023-06-03 00:34
Hi @MingboPeng, this is actually not a bug. When you use ScheduleRules for creating a schedule, you will need a base schedule rule for the whole year before adding a schedule rule that only applies to several months.
![image](https://github.com/MingboPeng/Ironbug/assets/9031066/4026093f-eea2-439b-8a51-025ff56eff35)
I added a note here as a reminder when there is only one schedule rule.
![image](https://github.com/MingboPeng/Ironbug/assets/9031066/79f04808-87a5-4181-aeb9-16be0127c5ff)

**Comment by MingboPeng** [comment] 2023-06-03 00:35
I am closing this issue unless you think otherwise.

**Comment by GudaoStudio** [comment] 2023-06-03 02:09
Thank you for your reply, I have made some more attempts.

This sounds like the input method of Fixed Interval Schedule, but I tried to test it with the example you provided, and the result was still the same: the schedule rule is not applied in the calculation, what I mean is, in the output, it doesn't run as expected like the anticipated schedule.

In fact, after deleting the set period, there was no change in the result, maybe you should try to run a simple case and then check the result? If this request is not too presumptuous.

**Comment by GudaoStudio** [comment] 2023-06-03 02:22
I found similar questions on discourse, this seems to be an issue that has been overlooked. You can refer to the final replies on these two pages, their problems are roughly the same as mine.
[Weekday/Weekend Ironbug schedule not working](https://discourse.ladybug.tools/t/weekday-weekend-ironbug-schedule-not-working/19750/2)
[Ironbug_schedule(only specific time) is not working](https://discourse.ladybug.tools/t/weekday-weekend-ironbug-schedule-not-working/19750/1)

**Comment by MingboPeng** [comment] 2023-09-22 04:02
Fixed in https://github.com/MingboPeng/Ironbug/commit/97e2169505a7594f4658cdc3f8d2bcc7643f3e70

**Closed** 2023-09-22 12:57 UTC
